### ISSUE TITLE
请问有pdf吗？

### ISSUE THREAD

**Issue by Stinky-Tofu** [brucefan1983/CUDA-Programming#11]
你好，非常nice的一本书，但是平时习惯了看电子书，且电子书做笔记方便，所以想问一下，有没有pdf版的呢？

**Comment by brucefan1983** [comment]
暂时没有公开的。

**Comment by Luo-Chang** [comment]
可去 文泉书局 购买正版电子版

**Comment by brucefan1983** [comment]
本书没有正版电子版。

Chang Luo ***@***.***> 于 2021年9月20日周一 13:10写道：

**Comment by Luo-Chang** [comment]
文泉书局是清华出版社的在线电子书网站，那看来就是出版社自行售卖电子版了😅
