### ISSUE TITLE
97页 印刷错误 

### ISSUE THREAD

**Issue by anxingle** [brucefan1983/CUDA-Programming#13]
97页（第9章 原子函数的合理使用， 9.3.1 C++版本的开发）cutoff_square 取为 $1.9^2 A^2$。 应为  $ 1.9^2$:
![error](https://user-images.githubusercontent.com/8489818/142356892-3be225d9-f447-4a74-b812-4747d0034cf3.jpg)

**Comment by brucefan1983** [comment]
这里没有写错，因为这里的长度的单位是埃（Angstrom，简写为A）。

**Comment by anxingle** [comment]
原来如此。谢谢您。
