### ISSUE TITLE
P55 因为我们的CPU程序中的计算是串行的，其性能基本上与数组长度无关。

### ISSUE THREAD

**Issue by ronaldpan** [brucefan1983/CUDA-Programming#15]
这应该是“其性能基本上与数组长度N成正比”吧.

**Comment by fever-Wong** [comment]
谢谢，您发给我的邮件已经收到，我会尽快处理。Thank you,the email you sent me has been received and I will handle it as soon as possible.王景博fever wong

**Comment by brucefan1983** [comment]
“性能”一般是只程序的计算速度，即单位时间能处理的数据量，单位是比如”GB/s"。从这个角度来说，CPU程序的速度是不显著依赖于数组长度的。但GPU就不同了，当N很小时，GPU的性能基本上正比于N，只有当N很大时，GPU的性能才饱和。

哲勇
