### ISSUE TITLE
请教一下第51页的算术强度-理论寄存器带宽-每个FMA的操作数 是怎么求得的？

### ISSUE THREAD

**Issue by Arsmart123** [brucefan1983/CUDA-Programming#16]
![8967D61FB388618CD624DFBA2BE54F35](https://user-images.githubusercontent.com/65449458/157788762-78c90707-5455-4407-8b83-d55cca668c89.png)
此处的FMA只提到了 d=a*b+c，具体是怎么算的？因为这种公式可能可以引用到论文中，或许下一版可以增加一点介绍~比如专门增加一章讲解，CUDA程序性能衡量指标，以及对应的公式，工具。
书写的很好，感谢作者！

**Comment by fever-Wong** [comment]
谢谢，您发给我的邮件已经收到，我会尽快处理。Thank you,the email you sent me has been received and I will handle it as soon as possible.王景博fever wong

**Comment by brucefan1983** [comment]
这方面的专业知识我知道的并不多。如果是要在学术论文中引用，最好去找期刊文献或者更加权威的文档（特别是Nvidia的技术文档）。本书定位于入门水平，比较强调实用性，不追求理论深度。
