### ISSUE TITLE
是否有CUDA交流群？

### ISSUE THREAD

**Issue by Arsmart123** [brucefan1983/CUDA-Programming#18]
樊老师，您好！我已经阅读完了您的书籍，现在在使用CUDA开发一种高性能的算法，能比NV的某官方库更快。不知道您是否有类似于读者群之类的HPC交流群？我是某985大学的硕士，应该也可以为社群做出贡献。多谢！

**Comment by fever-Wong** [comment]
谢谢，您发给我的邮件已经收到，我会尽快处理。Thank you,the email you sent me has been received and I will handle it as soon as possible.王景博fever wong

**Comment by brucefan1983** [comment]
> 樊老师，您好！我已经阅读完了您的书籍，现在在使用CUDA开发一种高性能的算法，能比NV的某官方库更快。不知道您是否有类似于读者群之类的HPC交流群？我是某985大学的硕士，应该也可以为社群做出贡献。多谢！

非常不错。有很多群可以加入的:

- 《CUDA Professional》QQ 群：45157483
- 《GPUMD》QQ 群：887975816
