### ISSUE TITLE
extern __shared__ real s_y[];

### ISSUE THREAD

**Issue by wangzhankun** [brucefan1983/CUDA-Programming#20]
在 `08-shared-memory/reduce2gpu.cu`文件中有
```cpp
extern __shared__ real s_y[];
```
请问这里为什么可以使用`extern`呢？该数组是在哪里定义的呢？

**Comment by fever-Wong** [comment]
谢谢，您发给我的邮件已经收到，我会尽快处理。Thank you,the email you sent me has been received and I will handle it as soon as possible.王景博fever wong

**Comment by brucefan1983** [comment]
这是“动态"共享内存定义的语法，参见书的8.1.3节。
