### ISSUE TITLE
英文版第三章有错误

### ISSUE THREAD

**Issue by FlyingCarlos** [brucefan1983/CUDA-Programming#24]
这一行有问题，`__host__`运行在主机端
https://github.com/brucefan1983/CUDA-Programming/blob/54ecbf55d6a08650bd272e52b27e74af5b63ec8b/src/03-basic-framework/readme.md?plain=1#L185

**Comment by brucefan1983** [comment]
非常感谢，这一行是错误的、多余的，我会删除。

**Comment by FlyingCarlos** [comment]
已确认
