### ISSUE TITLE
 p39页上方第14行代码

### ISSUE THREAD

**Issue by MoMo569377793** [brucefan1983/CUDA-Programming#28]
这里的cudaGetErrorString后是否应该添加反斜杠 \ （github中的代码并没有分两行写）
我在vscode里键入同样的代码如果不加反斜杠会报错？

**Comment by fever-Wong** [comment]
谢谢，您发给我的邮件已经收到，我会尽快处理。Thank you,the email you sent me has been received and I will handle it as soon as possible.王景博fever wong

**Comment by brucefan1983** [comment]
你仔细看，书稿中的第14行代码被印刷成了两行而已。实际上只有一行的。

**Comment by brucefan1983** [comment]
这是书稿印刷的问题。所以，一般来说，代码以Github的为准。

**Comment by MoMo569377793** [comment]
好的，谢谢老师解答， 我看到了 左边的行号显示是一行
