### ISSUE TITLE
44页的cuda-memcheck工具无输出

### ISSUE THREAD

**Issue by MoMo569377793** [brucefan1983/CUDA-Programming#29]
为何对于去掉if的文件进行编译后，用cuda-memcheck工具检测错误会死循环，一直无输出
![image](https://github.com/brucefan1983/CUDA-Programming/assets/83206978/79534a14-6cf6-41da-98ab-cc240bf0addd)

**Comment by MoMo569377793** [comment]
目前我将原有cuda10.0卸载，重新安装11.1后，CUDA-MEMCHECK不会死循环，但对于去掉if的cu文件输出依旧是0 error

**Comment by brucefan1983** [comment]
这个问题也也无从判断。也许你修改代码有误，也许这个工具有什么问题。很难说。

**Comment by MoMo569377793** [comment]
谢谢老师回复，我估计可能是工具有些问题？我查到新版CUDA已经弃用了cuda-memcheck，改为compute-sanitizer
使用compute-sanitizer检查本程序可以发现有error
