### ISSUE TITLE
English?

### ISSUE THREAD

**Issue by rahulbhalley** [brucefan1983/CUDA-Programming#6]
Why Chinese people don't write English. It becomes totally hard to translate each sentence.

**Comment by brucefan1983** [comment]
This book will be published in Chinese first. I might translate it to
English later.

Zheyong

ਰਾਹੁਲ ਭੇਲੇ <notifications@github.com> 于 2020年3月26日周四 18:00写道：

**Comment by brucefan1983** [comment]
Now I am writing an English version of the book.

**Comment by DeepLearnerYe** [comment]
> Now I am writing an English version of the book.

Only 5 chapters are finished now. Is the task suspended?

**Comment by brucefan1983** [comment]
Yes, I have no time on this anymroe. And I think now with good LLMs, it is easy to translate the whole book to English automatically. The Chinese version is in the repo:

https://github.com/brucefan1983/CUDA-Programming/blob/master/src/book_draft.pdf

**Comment by brucefan1983** [comment]
I might clean up a little the Chinese draft, as readers pointed out a number of mistakes.
