### ISSUE TITLE
静态全局内存变量如何释放？

### ISSUE THREAD

**Issue by Xianqi-Zhang** [brucefan1983/CUDA-Programming#8]
老师好，
P59页“全局内存的生命周期不是由核函数决定的，而是由主机端决定的”，第10章代码，reduce2static.cu中，声明静态全局变量如下，
__device__ real static_y[GRID_SIZE]; 
但该数组并未释放。请问静态全局内存变量的生命周期？采用cudaFree(static_y)释放时报错，请问该如何释放该变量呢？

**Comment by brucefan1983** [comment]
你好，静态数组的内存不是动态分配的，所以不需要手动释放。产出它的可见单位后，会自动释放。

哲勇

Xianqi Zhang ***@***.***> 于 2021年3月27日周六 10:27写道：

**Comment by Xianqi-Zhang** [comment]
所以，代码里面 的static_y的声明，是在reduce函数之前，而不是在main函数的前面，是为了限制static_y的可见范围。但是生命周期，仍然是程序开始到结束，相比在main函数之前声明static_y，仅是可见范围不同，生命周期没有差别。
请问，限制可见范围，有什么特别的好处吗？

**Comment by brucefan1983** [comment]
我认为你的理解正确。我认为，C++编程中尽量限制一个变量的可见范围是好的做法。也就是说，要尽量晚地定义一个变量。或者说，在不得不定义一个变量时再定义。

**Comment by Xianqi-Zhang** [comment]
好的，谢谢老师解答
