### ISSUE TITLE
CUDA程序第一次运行时间？

### ISSUE THREAD

**Issue by Xianqi-Zhang** [brucefan1983/CUDA-Programming#9]
老师好，
P48页，”第一次计算时，机器（无论是CPU还是GPU）都可能处于预热状态，测得的时间往往偏大”
第一次运行CUDA程序，或者运行其他深度学习算法，模型载入后，第一次计算相比之后确实会非常耗时。请问第一次运行程序时，具体都是因为哪些原因导致计算较慢呢？

我查到可能的原因包括：即时编译、将内核传输到GPU内存，缓存内容
https://www.javaroad.cn/questions/137499#

请问此外还包含哪些原因吗？

**Comment by brucefan1983** [comment]
第一次运行CUDA程序时，到底做了哪些事情，我还真不清楚。不好意思啊，这个问题我回答不上来。也许主页的 QQ 群里有人知道。

**Comment by Xianqi-Zhang** [comment]
好的，谢谢老师
